### ISSUE TITLE
Trouble working with pl330

### ISSUE THREAD

**Issue by nburkitt** [jeremytrimble/ezdma#11]
Hi Jeremy.

I'm hoping to use ezdma in a project for work, but I'm not getting very far. It's likely that the problem stems from my lack of experience with the Linux DMA engine, and the usual difficulty of finding relevant documentation. I'm using the PL330 DMAC on a Zynq 70xx. The example you provide uses the AXI DMA IP, which has a very different device-tree node. 
I have to manually load (modprobe or insmod) the driver, which is a bit of a red flag. And when I do, ezdma_probe() is never called, and of course the /dev/* nodes are never created.
Have you tried ezdma with the Pl330, or do you know of anyone who has?
Here's some debug output that shows what little is happening in the driver on "modprobe ezdma."

Mar 30 01:56:48 snoodle-01 kernel: [ 5216.552188] ezdma: ezdma_driver_init()
Mar 30 01:56:48 snoodle-01 kernel: [ 5216.552214] ezdma: allocated chrdev region: Major: 246, Minor: 0-8
Mar 30 01:56:48 snoodle-01 kernel: [ 5216.552506] ezdma: platform_driver_register(ezdma) returned 0

Thanks,

-Nick

**Comment by jeremytrimble** [comment]
Hi Nick,

Yeah, the PL330 is pretty different from the AXI DMA.  In particular, it's not what the dmaengine API refers to as a "slave" DMA (where data is copied from/to main memory into a device that is not addressable memory).  Put another way, with "slave" DMA devices like the AXI DMA, you program a source address (for RAM-to-AXI-Stream transfers) or a destination address (for AXI-Stream-to-RAM transfers), but not both.

I believe the PL330 implements more of a general memory-to-memory interface (what the dmaengine API seems to call a "memcpy"-style interface) -- you program it with both a source and destination address and it copies data between the source and destination, which are both accessed over an address-oriented bus.  As such, it bears more resemblance to the AXI CDMA core.

Unfortunately, ezdma is really just designed to work with the slave DMA API (note the call to `dmaengine_prep_slave_sg()` [here](https://github.com/jeremytrimble/ezdma/blob/d9d5f3c06912918242499dab8489cb01b8f95684/drivers/dma/ezdma.c#L346).  ezdma could probably be modified to work with the "memcpy" dmaengine API (perhaps by using an ioctl() to set the destination address before a write() or to set the source address before a read()), but it would take some time to get working.

**Comment by nburkitt** [comment]
Hi Jeremy.

Thanks for the reply. But according to the [Zynq TRM](https://www.xilinx.com/support/documentation/user_guides/ug585-Zynq-7000-TRM.pdf), the on-chip PL330 can only be used to transfer data between memory and PL. That would seem to make it an ideal candidate for use with ezdma. But, clearly, I'll be blazing my own trail if I proceed. :-) If I learn any more, I'll post it here.
Thanks again,

-Nick

**Comment by jeremytrimble** [comment]
Nick,

Ah, you're right -- I see that the pl330 driver [implements prep_slave_sg() after all](https://github.com/Xilinx/linux-xlnx/blob/d00f0c819e7ad6eca6269ef9bae15c9ab44c458e/drivers/dma/pl330.c#L2707).  In that case, maybe post your devicetree entry and I can try to guess what might be going wrong...

**Comment by nburkitt** [comment]
Hi Jeremy.

Great - thanks again. Here's what I'm using, reverse-compiled from my DTB. The pl330 node is boilerplate from zynq-7000.dtsi:

```
        dmac@f8003000 {
            compatible = "arm,pl330", "arm,primecell";
            reg = <0xf8003000 0x1000>;
            interrupt-parent = <0x3>;
            interrupt-names = "abort", "dma0", "dma1", "dma2", "dma3", "dma4", "dma5", "dma6", "dma7";
            interrupts = <0x0 0xd 0x4 0x0 0xe 0x4 0x0 0xf 0x4 0x0 0x10 0x4 0x0 0x11 0x4 0x0 0x28 0x4 0x0 0x29 0x4 0x0 0x2a 0
            #dma-cells = <0x1>;
            #dma-channels = <0x8>;
            #dma-requests = <0x4>;
            clocks = <0x1 0x1b>;
            clock-names = "apb_pclk";
            linux,phandle = <0x9>;
            phandle = <0x9>;
        };

        ezdma@0 {
            comptible = "ezdma";
            dmas = <0x9 0x0>;
            dma-names = "dma_raw";
            ezdma,dirs = <0x1>;
        };
```
I'm using one of the Zynq Peripheral Request Interfaces to connect to an AXI FIFO, which may or may not  be a factor in the device-tree. As always, documentation on things like that is in short supply.
Any insight you could give would be appreciated.

-Nick

**Comment by jeremytrimble** [comment]
One quick thing to check: "compatible" appears to be misspelled in the ezdma node.

**Comment by nburkitt** [comment]
Hi Jeremy.

I will do my best not to think of the hours I've spent on this. 
Thanks for applying your excellent editing skills to my problem - you were most helpful.
ezdma_probe() is now being called, and my /dev node is being created. 
Is it too early in the day to start drinking?
Thanks again,

-Nick
