### ISSUE TITLE
DMA transactions read() or write() with size bigger than 32 kB DMA transactions, Is Possible??

### ISSUE THREAD

**Issue by rogumag** [jeremytrimble/ezdma#3]
Hi jeremy, in using your ezdma driver to work with DMA transactions. If make a read() and write() with 1KB, the drivers works very well. This is your loopback example. But in my application, in need to write() a 40kB and read() only 1 kB. Using your driver with this constraints, the make the Scatter Gatter table, starts the DMA transactions but the system halts waiting the DMA interrupt.
This is the output Linux console. I`m using the hardware loopback

ezdma: loop_tx: sg_alloc_table() returned 0
ezdma: loop_tx: get_user_pages_fast() returned 11, expected 11
ezdma: loop_tx: sgl[0]: page: dfbe1360, len: 4000, offset: 96
ezdma: loop_tx: sgl[1]: page: dfba0fc0, len: 4096, offset: 0
ezdma: loop_tx: sgl[2]: page: dfba05c0, len: 4096, offset: 0
ezdma: loop_tx: sgl[3]: page: dfbb2f40, len: 4096, offset: 0
ezdma: loop_tx: sgl[4]: page: dfbd8420, len: 4096, offset: 0
ezdma: loop_tx: sgl[5]: page: dfbb6780, len: 4096, offset: 0
ezdma: loop_tx: sgl[6]: page: dfbb3880, len: 4096, offset: 0
ezdma: loop_tx: sgl[7]: page: dfbb03a0, len: 4096, offset: 0
ezdma: loop_tx: sgl[8]: page: dfbb46e0, len: 4096, offset: 0
ezdma: loop_tx: sgl[9]: page: dfbafb60, len: 4096, offset: 0
ezdma: loop_tx: sgl[10]: page: dfbedec0, len: 96, offset: 0
ezdma: loop_tx: dma_map_sg() returned 11, expected 11
ezdma: loop_tx: issued pending for TX

The same app with only 10kB (only write() ) the driver works very good.
ezdma: loop_tx: sg_alloc_table() returned 0
ezdma: loop_tx: get_user_pages_fast() returned 3, expected 3
ezdma: loop_tx: sgl[0]: page: dfbb7920, len: 4000, offset: 96
ezdma: loop_tx: sgl[1]: page: dfbbd900, len: 4096, offset: 0
ezdma: loop_tx: sgl[2]: page: dfb9b5c0, len: 2144, offset: 0
ezdma: loop_tx: dma_map_sg() returned 3, expected 3
ezdma: loop_tx: issued pending for TX
ezdma: loop_tx: callback fired for TX
But if execute 3 times the app the systems halts waiting DMA interrupt.
I need some help to work with bigger sizes of DMA transactions,
Thank you

**Comment by jeremytrimble** [comment]
rogumag,

Not sure if this is the problem, but in the AXI DMA IP core, there's a configuration parameter called "Width of Buffer Length Register" -- see [Xilinx PG021](http://www.xilinx.com/support/documentation/ip_documentation/axi_dma/v7_1/pg021_axi_dma.pdf).

This parameter sets the maximum transfer size supported by the AXI DMA core -- the default is 14 bits, which gives a maximum transfer length of 16383 bytes.  Unfortunately there is no way for the AXI DMA driver to detect the width of the register at runtime, so it's possible that the driver is effectively setting the transfer length to a value that has been truncated to the width of the Buffer Length register, which might cause the hang.

You might want to make sure that your "Width of Buffer Length Register" is at least 16 bits to accommodate your 40kB writes.  This can be checked in the IP configuration parameters in Vivado.

Let me know how it goes.

**Comment by rogumag** [comment]
Hi, jeremy, i detect my problem. Your driver works very well. I´m using a loopback implementation with AXI Stream Data FIFO. First, the FIFO depth is only 4096 positions. if write max positions of this value the FIFO the system pauses the transactions and DMA do not complete the transaction (interrupt waiting). if nothing read data out of the FIFO once it is full, the DMA controller will not complete the transaction and the system hang. Second, if write 10 kB and only read 5 kB the AXI FIFO do not set Tlast and the DMA do not complete the transactions.
__
Thank you for your Colaboration and your driver.

**Comment by jeremytrimble** [comment]
Great! I'm glad it's working well for you.

Would you mind posting what version of Vivado and Linux you're using for future reference?

**Comment by rogumag** [comment]
Hi, i´m using Vivado 2016.2 and linux kernel 4.4..

**Comment by jeremytrimble** [comment]
Great. Good to know it's still compatible with newer stuff (I'm still on older versions of Vivado and Linux for most of my work).  Did you have to make any updates to the ezdma code (to get it to compile, etc.)?  If so, and you have time to send a pull request, I'd gladly accept your contributions.

**Comment by rogumag** [comment]
Hi jeremy, i haven´t made any modification of your code. your driver works very well with the new kernel versions.

**Comment by jeremytrimble** [comment]
OK great, glad to hear it.  Best of luck!  Closing.
